"""Input/Output operations for blastmini.

This module provides FASTA file parsing, index persistence, and result
output functions. All parsers are implemented from scratch without
external dependencies like Biopython.
"""

import gzip
import json
import os
from typing import Any, Dict, Iterator, List, Union

from .models import Hit, SequenceRecord


def parse_fasta(filepath: Union[str, os.PathLike]) -> Iterator[SequenceRecord]:
    """Parse FASTA file and yield SequenceRecord objects."""
    if not os.path.exists(filepath):
        raise FileNotFoundError(f"FASTA file not found: {filepath}")

    if str(filepath).endswith('.gz'):
        open_func = gzip.open
    else:
        open_func = open

    with open_func(filepath, 'rt') as handle:
        yield from _parse_fasta_stream(handle)


def _parse_fasta_stream(handle) -> Iterator[SequenceRecord]:
    """Internal streaming parser for FASTA format.

    This function assumes the handle is already open and handles
    the parsing logic without closing the handle.

    Args:
        handle: Open file-like object (text mode).

    Yields:
        SequenceRecord objects.

    Raises:
        ValueError: If a sequence header is found without sequence data.
    """
    current_id = ""
    current_desc = ""
    current_seq_lines = []

    for line_num, line in enumerate(handle, 1):
        line = line.rstrip('\n\r')

        # Skip empty lines
        if not line:
            continue

        # Parse header line
        if line.startswith('>'):
            # If we were building a record, yield it
            if current_id:
                if not current_seq_lines:
                    raise ValueError(
                        f"Sequence record '{current_id}' has no sequence data (line {line_num})"
                    )
                yield SequenceRecord(
                    id=current_id,
                    description=current_desc,
                    sequence=''.join(current_seq_lines)
                )
                current_seq_lines = []

            # Parse new header: ID first token, rest as description
            header_parts = line[1:].split(maxsplit=1)
            current_id = header_parts[0].strip()
            current_desc = header_parts[1].strip() if len(
                header_parts) > 1 else ""

            # Basic validation of ID
            if not current_id:
                raise ValueError(
                    f"Empty sequence ID on line {line_num}: {line}")

        # Parse sequence line (non-header)
        else:
            # Strip whitespace and validate characters
            seq_line = line.strip()
            if seq_line:
                # Basic validation: allow A-Z, N, and gaps
                # Note: More rigorous validation can be done by caller
                current_seq_lines.append(seq_line)

    # Yield the last record
    if current_id:
        if not current_seq_lines:
            raise ValueError(
                f"Sequence record '{current_id}' has no sequence data")
        yield SequenceRecord(
            id=current_id,
            description=current_desc,
            sequence=''.join(current_seq_lines)
        )


def parse_fasta_multi(filepath: Union[str, os.PathLike]) -> List[SequenceRecord]:
    """Parse FASTA file and return all records as a list.

    Convenience function for small files where streaming isn't necessary.

    Warning:
        For large files, use parse_fasta() iterator instead to avoid
        memory issues.

    Args:
        filepath: Path to FASTA file.

    Returns:
        List of all SequenceRecord objects in the file.

    Examples:
        >>> records = parse_fasta_multi("small.fa")
        >>> print(len(records))
        5
    """
    return list(parse_fasta(filepath))


def save_hits_to_tsv(hits: List[Hit], output_file: Union[str, os.PathLike]) -> None:
    """Save hit list to TSV file with header.

    Args:
        hits: List of Hit objects.
        output_file: Path to output TSV file.

    Examples:
        >>> hits = [Hit(query_id="Q1", subject_id="S1", score=100)]
        >>> save_hits_to_tsv(hits, "results.tsv")
    """
    with open(output_file, 'w') as f:
        f.write(Hit.tsv_header() + '\n')
        for hit in hits:
            f.write(hit.to_tsv() + '\n')


def load_hits_from_tsv(input_file: Union[str, os.PathLike]) -> List[Hit]:
    """Load hits from a TSV file generated by save_hits_to_tsv.

    Args:
        input_file: Path to TSV file.

    Returns:
        List of Hit objects.

    Raises:
        ValueError: If file format is invalid.
    """
    hits = []
    with open(input_file, 'r') as f:
        # Skip header
        header = f.readline()
        if not header.strip():
            raise ValueError("Empty TSV file")

        for line_num, line in enumerate(f, 2):
            line = line.strip()
            if not line:
                continue

            parts = line.split('\t')
            if len(parts) < 6:
                raise ValueError(
                    f"Line {line_num}: Expected at least 6 columns, got {len(parts)}")

            try:
                hit = Hit(
                    query_id=parts[0],
                    subject_id=parts[1],
                    score=int(parts[2]),
                    identity_percent=float(parts[3]),
                    alignment_length=int(parts[4]),
                    query_start=int(parts[5]) if parts[5] else -1,
                    query_end=int(parts[6]) if parts[6] else -1,
                    subject_start=int(parts[7]) if parts[7] else -1,
                    subject_end=int(parts[8]) if parts[8] else -1,
                    evalue=float(parts[9]) if parts[9] else None,
                    bit_score=float(parts[10]) if parts[10] else None,
                )
                hits.append(hit)
            except (ValueError, IndexError) as e:
                raise ValueError(f"Line {line_num}: Invalid format - {e}")

    return hits


def save_index(index: Dict[str, List[tuple]], index_file: Union[str, os.PathLike]) -> None:
    """Save k-mer index to JSON file.

    Args:
        index: Dictionary mapping k-mer string to list of (subject_id, position).
        index_file: Path to output JSON file.

    Note:
        The index is serialized as JSON where keys are k-mers and values
        are lists of [subject_id, position] arrays.

    Examples:
        >>> index = {"ATCG": [("S1", 0), ("S2", 10)]}
        >>> save_index(index, "index.json")
    """
    # Convert tuples to lists for JSON serialization
    serializable_index = {
        k: [[sid, pos] for sid, pos in positions]
        for k, positions in index.items()
    }

    with open(index_file, 'w') as f:
        json.dump(serializable_index, f, indent=2, sort_keys=True)


def load_index(index_file: Union[str, os.PathLike]) -> Dict[str, List[tuple]]:
    """Load k-mer index from JSON file.

    Args:
        index_file: Path to JSON index file.

    Returns:
        Dictionary mapping k-mer string to list of (subject_id, position).

    Examples:
        >>> index = load_index("index.json")
        >>> print(len(index))
        12345
    """
    with open(index_file, 'r') as f:
        loaded = json.load(f)

    # Convert lists back to tuples
    index = {}
    for kmer, positions in loaded.items():
        index[kmer] = [(sid, pos) for sid, pos in positions]

    return index


def count_sequences(filepath: Union[str, os.PathLike]) -> int:
    """Count number of sequences in a FASTA file.

    This is a lightweight function that only counts headers without
    storing sequence data.

    Args:
        filepath: Path to FASTA file.

    Returns:
        Number of sequences in the file.

    Examples:
        >>> count = count_sequences("database.fa")
        >>> print(f"Database contains {count} sequences")
    """
    count = 0
    for record in parse_fasta(filepath):
        count += 1
    return count


def get_sequence_stats(filepath: Union[str, os.PathLike]) -> Dict[str, Any]:
    """Get summary statistics for a FASTA file.

    Computes basic statistics including number of sequences, total
    length, min/max/mean length, and GC content.

    Args:
        filepath: Path to FASTA file.

    Returns:
        Dictionary with summary statistics.

    Examples:
        >>> stats = get_sequence_stats("database.fa")
        >>> print(f"Total length: {stats['total_length']}")
    """
    n_seqs = 0
    total_length = 0
    lengths = []
    gc_counts = []

    for record in parse_fasta(filepath):
        n_seqs += 1
        seq_len = len(record)
        total_length += seq_len
        lengths.append(seq_len)

        # Calculate GC content for this sequence
        seq_upper = record.sequence
        gc_count = seq_upper.count('G') + seq_upper.count('C')
        gc_counts.append(gc_count / seq_len if seq_len > 0 else 0.0)

    if n_seqs == 0:
        return {
            'n_sequences': 0,
            'total_length': 0,
            'min_length': 0,
            'max_length': 0,
            'mean_length': 0.0,
            'gc_content': 0.0,
        }

    return {
        'n_sequences': n_seqs,
        'total_length': total_length,
        'min_length': min(lengths),
        'max_length': max(lengths),
        'mean_length': sum(lengths) / n_seqs,
        'gc_content': sum(gc_counts) / n_seqs,
    }
